### ISSUE TITLE
Looking at the wrong directory

### ISSUE THREAD

**Issue by kevinxbrown** [bpmurray/node-red-contrib-ds18b20-sensor#1]
Hi, I installed the node on my early Pi (model a), and get the following error in Node-RED:
Inject failed:Error: ENOENT, no such file or directory '/sys/bus/w1/devices/28-035001bf46ff/w1_slave'

But looking at the pi:
pi@raspberrypi /sys/bus/w1/devices $ ls
28-031501bf46ff  w1_bus_master1
pi@raspberrypi /sys/bus/w1/devices $ cat 28-031501bf46ff/w1_slave 
bb 01 55 00 7f ff 0c 10 49 : crc=49 YES
bb 01 55 00 7f ff 0c 10 49 t=27687
pi@raspberrypi /sys/bus/w1/devices $ 

For some reason it appears the Node RED node is changing the 5th and 6th digit incorrectly. 
Any help you can give would be appreciated! 
Thanks, Kevin

**Comment by rseb** [comment]
Hello,

I've the same problem on a Pi B board.

I think the problem is line 79 in ds18b20-node.js witch is : 
var dir = dev.substr(10,2) + dev.substr(9,2) + dev.substr(6,2)
if you modify it to : 
var dir = dev.substr(10,2) + dev.substr(8,2) + dev.substr(6,2)
it seem's to work better.

Regards,

Seb.

**Comment by bpmurray** [comment]
Different approach now, so it should all be OK.
